packages:
  - "chrome-extension"

enableGlobalVirtualStore: false

overrides:
  '@types/react': 19.2.18
  '@types/react-dom': 19.2.4

trustPolicyExclude:
  - 'semver@6.3.1'

allowBuilds:
  '@clerk/shared': true
  '@parcel/watcher': true
  '@swc/core': true
  browser-tabs-lock: false
  bufferutil: false
  core-js: false
  esbuild: true
  lefthook: true
  msw: false
  sharp: true
  utf-8-validate: false

onlyBuiltDependencies:
  - '@clerk/shared'
  - '@parcel/watcher'
  - '@swc/core'
  - esbuild
  - lefthook
  - sharp
